### ISSUE TITLE
Support pagination in hardware-reservation

### ISSUE THREAD

**Issue by falfaro** [equinix/metal-cli#46]
Currently the `packet-cli hardware-reservation get` does not support any form of pagination. For example, to request 1000 records (instead of hard-coded limit of 10).

This can be achieved using `curl`:

```
curl -X GET --header 'Accept: application/json' \
  --header "X-Auth-Token: ${PACKET_TOKEN}" \
  "https://api.packet.net/projects/${SOURCE_PROJECT}/hardware-reservations?per_page=1000"
```

It would be nice if a command-line flag allowed the same.

**Comment by displague** [comment]
Hi @falfaro, sorry for the months-long delay in responding.

I think this bug may have been fixed in a newer release than the one you were using.  I can't pin down which date or version introduced the fix. I would recommend pulling down the latest copy and testing again with that.

If you have a development environment:
```
git clone https://github.com/packethost/packet-cli/
cd packet-cli
make install
```

Otherwise, until we release v0.0.8, you can give v0.0.7 a shot from the releases page: https://github.com/packethost/packet-cli/releases/tag/0.0.7

The default behavior within the CLI is to perform lists without pagination.  This can be seen here:

https://github.com/packethost/packet-cli/blob/master/cmd/retrieve_hardware_reservations.go#L41-L62

The default behavior of Packngo is to fetch all pages.

In order for a single page to be returned, the `listOpt` sent by the CLI to Packngo's `ListHardwareReservations` function would need to include a `Page` field with a non-default (non-zero) value.

https://github.com/packethost/packngo/blob/4867738f776936b4096ab2e5099227d7e4864b77/hardware_reservations.go#L42-L68

Let us know if updating to the latest version corrects the problem.

**Comment by displague** [comment]
This may be dependent on packethost/packngo#63 but I don't know why that is still open.
The work in https://github.com/packethost/packngo/pull/114 is probably what fixed pagination in the CLI but @t0mk said in the description that this was "partial" pagination support.

Unless I am missing something, I think hardware-reservations was covered.

**Comment by adrianfurlong** [comment]
Hi there,

I've just installed v0.1.1 and we're still seeing hardware-reservations returning just 10 lines.
